all: out1 out2 out3 out4

a.exe: main.cpp
	g++ main.cpp

out1: a.exe b1.in
	a.exe < b1.in > out1

out2: a.exe b2.in
	a.exe < b2.in > out2

out3: a.exe b3.in
	a.exe < b3.in > out3

out4: a.exe b4.in
	a.exe < b4.in > out4



